import { useMemo, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { AlertTriangle, Bell, CheckCircle2, CircleAlert, Info } from 'lucide-react'
import { PageHeader } from '@/components/PageHeader'
import { Card } from '@/components/ui'
import { StatusBadge } from '@/components/StatusBadge'
import { demoMines, demoNotifications } from '@/data/demo'

export const Route = createFileRoute('/app/notifications')({ component: NotificationsPage })
const icons={Critical:CircleAlert,Warning:AlertTriangle,Information:Info,Success:CheckCircle2}
function NotificationsPage(){const [filter,setFilter]=useState('All');const [notifications,setNotifications]=useState(demoNotifications);const records=useMemo(()=>notifications.filter(item=>filter==='All'||filter==='Unread'&&!item.read||item.type===filter),[filter,notifications]);return <><PageHeader eyebrow="Alerts and updates" title="Notifications" description="Review synthetic alerts, deadline warnings and workflow updates across the demo portfolio." action={<button onClick={()=>setNotifications(items=>items.map(item=>({...item,read:true})))} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Mark all as read</button>}/><div className="mb-5 flex flex-wrap gap-2">{['All','Unread','Critical','Warning'].map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${filter===item?'bg-emerald-950 text-white':'border border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`}>{item}</button>)}</div><Card className="overflow-hidden"><div className="divide-y divide-slate-100">{records.map(notification=>{const Icon=icons[notification.type];const mine=demoMines.find(item=>item.id===notification.mineId);return <article key={notification.id} className={`flex gap-4 p-5 sm:p-6 ${notification.read?'bg-white':'bg-amber-50/35'}`}><div className={`grid size-11 shrink-0 place-items-center rounded-xl ${notification.type==='Critical'?'bg-red-100 text-red-800':notification.type==='Warning'?'bg-amber-100 text-amber-800':notification.type==='Success'?'bg-emerald-100 text-emerald-800':'bg-blue-100 text-blue-800'}`}><Icon className="size-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-900">{notification.title}</h2>{!notification.read&&<button onClick={()=>setNotifications(items=>items.map(item=>item.id===notification.id?{...item,read:true}:item))} className="rounded-full bg-blue-700 px-2 py-0.5 text-[10px] font-bold uppercase text-white">Mark read</button>}<StatusBadge status={notification.type}/></div><p className="mt-2 text-sm leading-6 text-slate-600">{notification.description}</p>{mine&&<p className="mt-2 text-xs font-semibold text-slate-500">Related mine: {mine.name}</p>}</div><time className="whitespace-nowrap text-xs text-slate-400">{notification.timestamp}</time></div></div></article>})}{records.length===0&&<div className="p-12 text-center"><Bell className="mx-auto size-8 text-slate-300"/><p className="mt-3 text-sm text-slate-500">No notifications match this filter.</p></div>}</div></Card></>}
