import { createFileRoute } from '@tanstack/react-router'
import { BadgeCheck, Building2, Mail, MapPin, Shield, UserRound } from 'lucide-react'
import { PageHeader } from '@/components/PageHeader'
import { Card } from '@/components/ui'
import { useSession } from '@/context/SessionContext'
import { demoMines } from '@/data/demo'
import { rolePermissions } from '@/config/app'

export const Route = createFileRoute('/app/profile')({ component: ProfilePage })
function ProfilePage(){const {session}=useSession();if(!session)return null;const mine=demoMines.find(item=>item.id===session.assignedMineId);const fields=[['Name',session.name],['Role',session.role],['Employee ID',session.employeeId??'Not assigned in Demo Mode'],['Organization',session.organization],['Department',session.department],['Assigned Mine',mine?.name??'Portfolio-level access'],['Email',session.email??'Not used in Demo Mode']];return <><PageHeader eyebrow="Session identity" title="User profile" description="Profile information comes from the active session abstraction rather than hard-coded employee identities."/><div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Card className="overflow-hidden"><div className="bg-emerald-950 p-7 text-white"><div className="grid size-16 place-items-center rounded-2xl bg-amber-400 text-xl font-bold text-emerald-950">DU</div><h2 className="mt-5 font-display text-2xl font-semibold">{session.name}</h2><p className="mt-1 text-sm text-emerald-100/65">{session.role}</p><div className="mt-5 inline-flex items-center gap-2 rounded-lg bg-amber-300/10 px-3 py-2 text-xs font-bold uppercase tracking-[.15em] text-amber-300"><BadgeCheck className="size-4"/>Demo Mode</div></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Role scope</p><ul className="mt-4 space-y-3">{rolePermissions[session.role].map(item=><li key={item} className="flex items-center gap-3 text-sm text-slate-600"><Shield className="size-4 text-emerald-700"/>{item}</li>)}</ul></div></Card><Card className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Session details</p><div className="mt-5 grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-2">{fields.map(([label,value],index)=>{const icons=[UserRound,Shield,BadgeCheck,Building2,Building2,MapPin,Mail];const Icon=icons[index];return <div key={label} className="bg-white p-5"><div className="flex items-center gap-2 text-xs font-semibold text-slate-400"><Icon className="size-4"/>{label}</div><p className="mt-2 text-sm font-semibold text-slate-800">{value}</p></div>})}</div><div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-800">This profile represents a temporary demonstration session. Permanent identity fields populate only after a real authentication and user approval workflow is connected.</div></Card></div></>}
