import { useMemo, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { SlidersHorizontal } from 'lucide-react'
import { PageHeader } from '@/components/PageHeader'
import { Card, Select } from '@/components/ui'
import { DataTable, type TableColumn } from '@/components/DataTable'
import { StatusBadge } from '@/components/StatusBadge'
import { complianceBreakdown, demoCompliance, demoMines } from '@/data/demo'
import type { ComplianceRecord } from '@/types/domain'

export const Route = createFileRoute('/app/compliance')({ component: CompliancePage })
const mineName=(id:string)=>demoMines.find(mine=>mine.id===id)?.name??'Unknown demo mine'
const columns:TableColumn<ComplianceRecord>[]=[
  {key:'requirement',label:'Requirement',render:record=><div><p className="font-semibold text-slate-900">{record.requirement}</p><p className="mt-1 text-xs text-slate-400">{record.id}</p></div>},
  {key:'category',label:'Category',render:record=>record.category}, {key:'mine',label:'Mine',render:record=>mineName(record.mineId)}, {key:'due',label:'Due Date',render:record=>record.dueDate}, {key:'status',label:'Status',render:record=><StatusBadge status={record.status}/>}, {key:'risk',label:'Risk',render:record=><StatusBadge status={record.risk}/>}, {key:'department',label:'Responsible Department',render:record=>record.responsibleDepartment},
]
function CompliancePage(){const [category,setCategory]=useState('All');const [status,setStatus]=useState('All');const [risk,setRisk]=useState('All');const [mine,setMine]=useState('All');const records=useMemo(()=>demoCompliance.filter(record=>(category==='All'||record.category===category)&&(status==='All'||record.status===status)&&(risk==='All'||record.risk===risk)&&(mine==='All'||record.mineId===mine)),[category,status,risk,mine]);return <><PageHeader eyebrow="Compliance monitoring" title="Compliance overview" description="Track synthetic requirements by category, status, risk and responsible department."/><div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{complianceBreakdown.map(({category:label,value})=><Card key={label} className="p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-emerald-950">{value}%</p></Card>)}</div><Card className="mb-5 p-4"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-slate-400"><SlidersHorizontal className="size-4"/>Filter records</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label><span className="sr-only">Category</span><Select className="mt-0" value={category} onChange={event=>setCategory(event.target.value)}><option>All</option><option>Safety</option><option>Environment</option><option>Labour</option><option>Operations</option></Select></label><label><span className="sr-only">Status</span><Select className="mt-0" value={status} onChange={event=>setStatus(event.target.value)}><option>All</option><option>Compliant</option><option>Due Soon</option><option>Pending</option><option>Overdue</option><option>Non-Compliant</option></Select></label><label><span className="sr-only">Risk</span><Select className="mt-0" value={risk} onChange={event=>setRisk(event.target.value)}><option>All</option><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></Select></label><label><span className="sr-only">Mine</span><Select className="mt-0" value={mine} onChange={event=>setMine(event.target.value)}><option value="All">All mines</option>{demoMines.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></label></div></Card><DataTable rows={records} columns={columns}/></>}
