import { useState, type FormEvent } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { AuthLayout } from '@/components/AuthLayout'
import { Button, Field, Input, Select } from '@/components/ui'
import { publicRoles } from '@/config/app'
import { prototypeAuthService } from '@/services/auth'
import type { PublicRole } from '@/types/domain'

export const Route = createFileRoute('/create-account')({ component: CreateAccountPage })
function CreateAccountPage(){const [message,setMessage]=useState('');const [error,setError]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=new FormData(event.currentTarget);if(form.get('password')!==form.get('confirmPassword')){setError('Passwords must match.');return}const result=await prototypeAuthService.signUp({fullName:String(form.get('fullName')),email:String(form.get('email')),requestedRole:String(form.get('role')) as PublicRole});setMessage(result.message)}return <AuthLayout eyebrow="Access request" title="Create an account request" description="Requested roles require organizational authorization in a future phase. Privileged administration is never publicly self-assignable."><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2">{(message||error)&&<div className={`sm:col-span-2 rounded-xl border p-4 text-sm ${error?'border-red-200 bg-red-50 text-red-800':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error||message}</div>}<Field label="Full Name"><Input name="fullName" required autoComplete="name"/></Field><Field label="Email"><Input name="email" type="email" required autoComplete="email"/></Field><Field label="Password"><Input name="password" type="password" required minLength={8} autoComplete="new-password"/></Field><Field label="Confirm Password"><Input name="confirmPassword" type="password" required minLength={8} autoComplete="new-password"/></Field><Field label="Organization"><Input name="organization" required/></Field><Field label="Employee ID" hint="Optional"><Input name="employeeId"/></Field><Field label="Department"><Input name="department" required/></Field><Field label="Requested Role"><Select name="role" required>{publicRoles.map(role=><option key={role}>{role}</option>)}</Select></Field><Field label="Mine / Location" hint="If applicable"><Input name="mine"/></Field><Field label="Phone Number" hint="Optional"><Input name="phone" type="tel" autoComplete="tel"/></Field><label className="flex gap-3 text-sm text-slate-600 sm:col-span-2"><input type="checkbox" required className="mt-1 size-4 accent-emerald-900"/><span>I agree to the Terms and Conditions and understand that access remains subject to organizational verification and approval.</span></label><Button type="submit" className="sm:col-span-2">Submit Account Request</Button><p className="text-center text-sm text-slate-500 sm:col-span-2">Already have an account? <Link to="/sign-in" className="font-semibold text-emerald-800">Sign In</Link></p></form></AuthLayout>}
