/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrganizationRouteImport } from './routes/app.organization'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMinesRouteImport } from './routes/app.mines'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppModuleRouteImport } from './routes/app.$module'
import { Route as AppMinesIndexRouteImport } from './routes/app.mines.index'
import { Route as AppMinesMineIdRouteImport } from './routes/app.mines.$mineId'
import { Route as AppInspectionsCreateRouteImport } from './routes/app.inspections.create'
import { Route as AppInspectionsIdRouteImport } from './routes/app.inspections.$id'
import { Route as AppInspectionsIdReportRouteImport } from './routes/app.inspections.$id.report'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMinesRoute = AppMinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppMinesIndexRoute = AppMinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMinesRoute,
} as any)
const AppMinesMineIdRoute = AppMinesMineIdRouteImport.update({
  id: '/$mineId',
  path: '/$mineId',
  getParentRoute: () => AppMinesRoute,
} as any)
const AppInspectionsCreateRoute = AppInspectionsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppInspectionsRoute,
} as any)
const AppInspectionsIdRoute = AppInspectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInspectionsRoute,
} as any)
const AppInspectionsIdReportRoute = AppInspectionsIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppInspectionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/app/$module': typeof AppModuleRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/inspections': typeof AppInspectionsRouteWithChildren
  '/app/mines': typeof AppMinesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/inspections/$id': typeof AppInspectionsIdRouteWithChildren
  '/app/inspections/create': typeof AppInspectionsCreateRoute
  '/app/mines/$mineId': typeof AppMinesMineIdRoute
  '/app/mines/': typeof AppMinesIndexRoute
  '/app/inspections/$id/report': typeof AppInspectionsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/app/$module': typeof AppModuleRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/inspections': typeof AppInspectionsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/inspections/$id': typeof AppInspectionsIdRouteWithChildren
  '/app/inspections/create': typeof AppInspectionsCreateRoute
  '/app/mines/$mineId': typeof AppMinesMineIdRoute
  '/app/mines': typeof AppMinesIndexRoute
  '/app/inspections/$id/report': typeof AppInspectionsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/app/$module': typeof AppModuleRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/inspections': typeof AppInspectionsRouteWithChildren
  '/app/mines': typeof AppMinesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/inspections/$id': typeof AppInspectionsIdRouteWithChildren
  '/app/inspections/create': typeof AppInspectionsCreateRoute
  '/app/mines/$mineId': typeof AppMinesMineIdRoute
  '/app/mines/': typeof AppMinesIndexRoute
  '/app/inspections/$id/report': typeof AppInspectionsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create-account'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/app/$module'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/inspections'
    | '/app/mines'
    | '/app/notifications'
    | '/app/organization'
    | '/app/profile'
    | '/app/inspections/$id'
    | '/app/inspections/create'
    | '/app/mines/$mineId'
    | '/app/mines/'
    | '/app/inspections/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/create-account'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/app/$module'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/inspections'
    | '/app/notifications'
    | '/app/organization'
    | '/app/profile'
    | '/app/inspections/$id'
    | '/app/inspections/create'
    | '/app/mines/$mineId'
    | '/app/mines'
    | '/app/inspections/$id/report'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/create-account'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/app/$module'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/inspections'
    | '/app/mines'
    | '/app/notifications'
    | '/app/organization'
    | '/app/profile'
    | '/app/inspections/$id'
    | '/app/inspections/create'
    | '/app/mines/$mineId'
    | '/app/mines/'
    | '/app/inspections/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mines': {
      id: '/app/mines'
      path: '/mines'
      fullPath: '/app/mines'
      preLoaderRoute: typeof AppMinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mines/': {
      id: '/app/mines/'
      path: '/'
      fullPath: '/app/mines/'
      preLoaderRoute: typeof AppMinesIndexRouteImport
      parentRoute: typeof AppMinesRoute
    }
    '/app/mines/$mineId': {
      id: '/app/mines/$mineId'
      path: '/$mineId'
      fullPath: '/app/mines/$mineId'
      preLoaderRoute: typeof AppMinesMineIdRouteImport
      parentRoute: typeof AppMinesRoute
    }
    '/app/inspections/create': {
      id: '/app/inspections/create'
      path: '/create'
      fullPath: '/app/inspections/create'
      preLoaderRoute: typeof AppInspectionsCreateRouteImport
      parentRoute: typeof AppInspectionsRoute
    }
    '/app/inspections/$id': {
      id: '/app/inspections/$id'
      path: '/$id'
      fullPath: '/app/inspections/$id'
      preLoaderRoute: typeof AppInspectionsIdRouteImport
      parentRoute: typeof AppInspectionsRoute
    }
    '/app/inspections/$id/report': {
      id: '/app/inspections/$id/report'
      path: '/report'
      fullPath: '/app/inspections/$id/report'
      preLoaderRoute: typeof AppInspectionsIdReportRouteImport
      parentRoute: typeof AppInspectionsIdRoute
    }
  }
}

interface AppInspectionsIdRouteChildren {
  AppInspectionsIdReportRoute: typeof AppInspectionsIdReportRoute
}

const AppInspectionsIdRouteChildren: AppInspectionsIdRouteChildren = {
  AppInspectionsIdReportRoute: AppInspectionsIdReportRoute,
}

const AppInspectionsIdRouteWithChildren =
  AppInspectionsIdRoute._addFileChildren(AppInspectionsIdRouteChildren)

interface AppInspectionsRouteChildren {
  AppInspectionsIdRoute: typeof AppInspectionsIdRouteWithChildren
  AppInspectionsCreateRoute: typeof AppInspectionsCreateRoute
}

const AppInspectionsRouteChildren: AppInspectionsRouteChildren = {
  AppInspectionsIdRoute: AppInspectionsIdRouteWithChildren,
  AppInspectionsCreateRoute: AppInspectionsCreateRoute,
}

const AppInspectionsRouteWithChildren = AppInspectionsRoute._addFileChildren(
  AppInspectionsRouteChildren,
)

interface AppMinesRouteChildren {
  AppMinesMineIdRoute: typeof AppMinesMineIdRoute
  AppMinesIndexRoute: typeof AppMinesIndexRoute
}

const AppMinesRouteChildren: AppMinesRouteChildren = {
  AppMinesMineIdRoute: AppMinesMineIdRoute,
  AppMinesIndexRoute: AppMinesIndexRoute,
}

const AppMinesRouteWithChildren = AppMinesRoute._addFileChildren(
  AppMinesRouteChildren,
)

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppInspectionsRoute: typeof AppInspectionsRouteWithChildren
  AppMinesRoute: typeof AppMinesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppInspectionsRoute: AppInspectionsRouteWithChildren,
  AppMinesRoute: AppMinesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
