/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrganizationRouteImport } from './routes/app.organization'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMinesRouteImport } from './routes/app.mines'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppModuleRouteImport } from './routes/app.$module'
import { Route as AppMinesIndexRouteImport } from './routes/app.mines.index'
import { Route as AppMinesMineIdRouteImport } from './routes/app.mines.$mineId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMinesRoute = AppMinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppMinesIndexRoute = AppMinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMinesRoute,
} as any)
const AppMinesMineIdRoute = AppMinesMineIdRouteImport.update({
  id: '/$mineId',
  path: '/$mineId',
  getParentRoute: () => AppMinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/app/$module': typeof AppModuleRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/mines': typeof AppMinesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/mines/$mineId': typeof AppMinesMineIdRoute
  '/app/mines/': typeof AppMinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/app/$module': typeof AppModuleRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/mines/$mineId': typeof AppMinesMineIdRoute
  '/app/mines': typeof AppMinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/app/$module': typeof AppModuleRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/mines': typeof AppMinesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/mines/$mineId': typeof AppMinesMineIdRoute
  '/app/mines/': typeof AppMinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create-account'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/app/$module'
    | '/app/compliance'
    | '/app/mines'
    | '/app/notifications'
    | '/app/organization'
    | '/app/profile'
    | '/app/'
    | '/app/mines/$mineId'
    | '/app/mines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/app/$module'
    | '/app/compliance'
    | '/app/notifications'
    | '/app/organization'
    | '/app/profile'
    | '/app'
    | '/app/mines/$mineId'
    | '/app/mines'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/create-account'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/app/$module'
    | '/app/compliance'
    | '/app/mines'
    | '/app/notifications'
    | '/app/organization'
    | '/app/profile'
    | '/app/'
    | '/app/mines/$mineId'
    | '/app/mines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mines': {
      id: '/app/mines'
      path: '/mines'
      fullPath: '/app/mines'
      preLoaderRoute: typeof AppMinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mines/': {
      id: '/app/mines/'
      path: '/'
      fullPath: '/app/mines/'
      preLoaderRoute: typeof AppMinesIndexRouteImport
      parentRoute: typeof AppMinesRoute
    }
    '/app/mines/$mineId': {
      id: '/app/mines/$mineId'
      path: '/$mineId'
      fullPath: '/app/mines/$mineId'
      preLoaderRoute: typeof AppMinesMineIdRouteImport
      parentRoute: typeof AppMinesRoute
    }
  }
}

interface AppMinesRouteChildren {
  AppMinesMineIdRoute: typeof AppMinesMineIdRoute
  AppMinesIndexRoute: typeof AppMinesIndexRoute
}

const AppMinesRouteChildren: AppMinesRouteChildren = {
  AppMinesMineIdRoute: AppMinesMineIdRoute,
  AppMinesIndexRoute: AppMinesIndexRoute,
}

const AppMinesRouteWithChildren = AppMinesRoute._addFileChildren(
  AppMinesRouteChildren,
)

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppMinesRoute: typeof AppMinesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppMinesRoute: AppMinesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
